// VGA color palette
.equ VGA_BLACK	=	0x0000
.equ VGA_WHITE	=	0xFFFF
.equ VGA_RED	=	0xF800
.equ VGA_GREEN	=	0x0400
.equ VGA_BLUE	=	0x001F
.equ VGA_SILVER	=	0xC618
.equ VGA_GRAY	=	0x8410
.equ VGA_MAROON	=	0x8000
.equ VGA_YELLOW	=	0xFFE0
.equ VGA_OLIVE	=	0x8400
.equ VGA_LIME	=	0x07E0
.equ VGA_AQUA	=	0x07FF
.equ VGA_TEAL	=	0x0410
.equ VGA_NAVY	=	0x0010
.equ VGA_FUCHSIA=	0xF81F
.equ VGA_PURPLE	=   0x8010
